[project]
name = "anisecord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "functions-framework>=3.10.0",
    "litellm>=1.80.9",
    "pynacl>=1.6.1",
    "requests>=2.32.5",
]
